### PR TITLE
README: add website url

### PR DESCRIPTION
**Pull request by nikhita**
I was just talking to @p0lyn0mial about this project yesterday, since he mentioned that he had ideas about improving documentation around some of the pain points in client-go. While doing so, I couldn't remember the URL we had set up. :grimacing: 

Just adding it here so that's easy to figure it out when we start devoting time to this project again.

### CODE REVIEW

**Comment by nikhita** [comment]
O_o

**Review by lilic — APPROVED** [review]
lgtm, thanks!! :) 

We should really do more, I keep forgetting 😞 Will try to take some time this or next weekend to come up with some ideas and drafts!

**Comment by nikhita** [comment]
Would be neat if we could try to cook up something before KubeCon ;)

I'm not sure what's up with the cla. Manually merging this.

**Pull request merged**
